# Configuration file

# pv settings
pv_data_path: "weather_data/pv_data.csv"
pv_data_column: "PV Power"  #enter name of the column to get normed fixed values for Flow (value between 0 and 1)
pv_nominal_value: 80.000000  # pv_nominal_value [W], e.g. 5000000 = 5MW
pv_variable_costs: 0  # set 0 so that all of the electricity from renewables is taken

# wind settings
wind_data_path: "weather_data/example_data_hourly.csv"
wind_data_column: "P_wp" #enter name of the column to get normed fixed values for Flow (value between 0 and 1)
wind_nominal_value: 80.000000  # wind_nominal_value [W], e.g. 10000000 = 10MW
wind_variable_costs: 0  # set 0 so that all of the electricity from renewables is taken

# grid settings
grid_nominal_value: 130.000000 #to make dynamic
grid_variable_costs: 2.6 # 0.16 $/kWh --> 0.00016

# h2_ship_source settings
h2_ship_nominal_value: 5000 # kg / h
h2_ship_variable_costs: 2

# electrolyzer settings
electrolyzer_nominal_value: 100.000000 #Annahme 10 Elektrolyseure 10* 10MW (Plug. EX-4250D System Specifications.)
h2_produced: 1800 #kg/h gerundet aus 10* 10 MW Elektrolyzeur (Plug. EX-4250D System Specifications.)
electrolyzer_variable_costs: 0

# h2_storage settings
h2_storage_loss_rate: 0
h2_storage_nominal_storage_capacity: 600 #kg H2 Speicherung (APEX. Elektrolyseur Daten, 2023.)

# steel mill
steel_mill_power: 2 
#electricity_to_steel_max: 205200000 #Annahme bei 3,6 Mio t Stahl pro Jahr bei 500kWh entspricht einer Leistung von 3,6 Mio t 57MW = 205,2 MW
steel_mill_variable_costs: 0  # to prefer steel mill over electrolyzer 
h2_for_steel: 41.09589  # kg h2/ kg steel     DRI steel 90 - 130kg / t steel (M. Shahabuddin, Alireza Rahbari, Shabnam Sabah, Geoffrey Brooks, John Pye, & and M. Akbar Rhamdhani. Process modelling for the production of hydrogen-based direct reduced iron in shaft furnaces using different ore grades.)
electricity_for_steel: 1.52876  # MWh / kg   3,787 MWh / t * 410,9 = 1528,76 MWh =^ 1,52876 MWh/ kg liquid steel EAF DRI Standort Hamburg (Elsheikh, H., & Eveloy, V. (2023). Renewable hydrogen based direct iron ore reduction and steel making with grid assistance. Energy Conversion and Management, 297, 117544. https://doi.org/10.1016/j.enconman.2023.117544)
                              # 3,72 MWh (Bhaskar, A., Assadi, M., & Somehsaraei, H. N. (2020). Decarbonization of the Iron and Steel Industry with Direct Reduction of Iron Ore with Green Hydrogen. Energies. Advance online publication. https://doi.org/10.3390/en13030758)

#steel 
steel_price: -10
steel_produced: 410959 # kg / h, 410.959 t / h,  3,6 Mio t Stahl pro Jahr =^ 410,95 t / h (ArcelorMittal. (2024, September 25). Smarter steels for people and planet - Startschuss für Wasserstoffproduktion mit Hybit in Bremen. ICT Solutions GmbH Trier - www.ict.ag.)
steel_produced_max: 

# electricity slack
electricity_slack_variable_costs: 1000

# co2 emissions
co2_emissions: 0.500 # kg/kWh     500 g/kWh   # spezifischer Treibhausgas emissionen strommix (Icha, P., & Lauf, T. (2024). Umweltbundesamt)

#solver settings
solver: "cbc" #decide which solver is chosen... (garubi, glpk,...)
